-- MySQL Script generated by MySQL Workbench
-- 08/27/18 20:21:50
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema bdgrc
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bdgrc
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bdgrc` DEFAULT CHARACTER SET utf8 ;
USE `bdgrc` ;

-- -----------------------------------------------------
-- Table `bdgrc`.`Grupo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdgrc`.`Grupo` (
  `idGrupo` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(300) NULL,
  PRIMARY KEY (`idGrupo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdgrc`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdgrc`.`Usuario` (
  `idUsuario` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idUsuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdgrc`.`Libro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdgrc`.`Libro` (
  `idLibro` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `autor` VARCHAR(45) NOT NULL,
  `ISBN` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idLibro`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdgrc`.`Referencia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdgrc`.`Referencia` (
  `idReferencia` INT NOT NULL AUTO_INCREMENT,
  `texto` VARCHAR(300) NULL,
  `fechaHora` DATETIME NOT NULL,
  `tags` VARCHAR(200) NULL,
  `idUsuario` INT NOT NULL,
  `idGrupo` INT NOT NULL,
  `idLibro` INT NULL,
  PRIMARY KEY (`idReferencia`),
  INDEX `fk_Referencia_Usuario1_idx` (`idUsuario` ASC),
  INDEX `fk_Referencia_Grupo1_idx` (`idGrupo` ASC),
  INDEX `fk_Referencia_Libro1_idx` (`idLibro` ASC),
  CONSTRAINT `fk_Referencia_Usuario1`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `bdgrc`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Referencia_Grupo1`
    FOREIGN KEY (`idGrupo`)
    REFERENCES `bdgrc`.`Grupo` (`idGrupo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Referencia_Libro1`
    FOREIGN KEY (`idLibro`)
    REFERENCES `bdgrc`.`Libro` (`idLibro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdgrc`.`Comentario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdgrc`.`Comentario` (
  `idComentario` INT NOT NULL AUTO_INCREMENT,
  `comentario` VARCHAR(300) NULL,
  `fechaHora` DATETIME NOT NULL,
  `idReferencia` INT NOT NULL,
  `idUsuario` INT NOT NULL,
  PRIMARY KEY (`idComentario`, `idReferencia`, `idUsuario`),
  INDEX `fk_Comentario_Referencia1_idx` (`idReferencia` ASC),
  INDEX `fk_Comentario_Usuario1_idx` (`idUsuario` ASC),
  CONSTRAINT `fk_Comentario_Referencia1`
    FOREIGN KEY (`idReferencia`)
    REFERENCES `bdgrc`.`Referencia` (`idReferencia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Comentario_Usuario1`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `bdgrc`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdgrc`.`Grupo_has_Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdgrc`.`Grupo_has_Usuario` (
  `Grupo_idGrupo` INT NOT NULL,
  `Usuario_idUsuario` INT NOT NULL,
  `permisoUsuario` ENUM('asd') NULL,
  PRIMARY KEY (`Grupo_idGrupo`, `Usuario_idUsuario`),
  INDEX `fk_Grupo_has_Usuario_Usuario1_idx` (`Usuario_idUsuario` ASC),
  INDEX `fk_Grupo_has_Usuario_Grupo_idx` (`Grupo_idGrupo` ASC),
  CONSTRAINT `fk_Grupo_has_Usuario_Grupo`
    FOREIGN KEY (`Grupo_idGrupo`)
    REFERENCES `bdgrc`.`Grupo` (`idGrupo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Grupo_has_Usuario_Usuario1`
    FOREIGN KEY (`Usuario_idUsuario`)
    REFERENCES `bdgrc`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdgrc`.`URL`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdgrc`.`URL` (
  `idURL` INT NOT NULL AUTO_INCREMENT,
  `url` VARCHAR(200) NOT NULL,
  `idReferencia` INT NOT NULL,
  PRIMARY KEY (`idURL`),
  INDEX `fk_URL_Referencia1_idx` (`idReferencia` ASC),
  CONSTRAINT `fk_URL_Referencia1`
    FOREIGN KEY (`idReferencia`)
    REFERENCES `bdgrc`.`Referencia` (`idReferencia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdgrc`.`Tag`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdgrc`.`Tag` (
  `idTag` INT NOT NULL AUTO_INCREMENT,
  `etiqueta` VARCHAR(100) NULL,
  PRIMARY KEY (`idTag`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdgrc`.`Tag_has_Referencia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdgrc`.`Tag_has_Referencia` (
  `idTag` INT NOT NULL,
  `idReferencia` INT NOT NULL,
  PRIMARY KEY (`idTag`, `idReferencia`),
  INDEX `fk_Tag_has_Referencia_Referencia1_idx` (`idReferencia` ASC),
  INDEX `fk_Tag_has_Referencia_Tag1_idx` (`idTag` ASC),
  CONSTRAINT `fk_Tag_has_Referencia_Tag1`
    FOREIGN KEY (`idTag`)
    REFERENCES `bdgrc`.`Tag` (`idTag`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Tag_has_Referencia_Referencia1`
    FOREIGN KEY (`idReferencia`)
    REFERENCES `bdgrc`.`Referencia` (`idReferencia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
