-- MySQL Script generated by MySQL Workbench
-- Sat May  4 14:16:39 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema bdgrc
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bdgrc
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bdgrc` DEFAULT CHARACTER SET utf8 ;
USE `bdgrc` ;

-- -----------------------------------------------------
-- Table `bdgrc`.`grupo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdgrc`.`grupo` (
  `idGrupo` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(300) NULL DEFAULT NULL,
  `imagenGrupo` MEDIUMBLOB NULL DEFAULT NULL,
  PRIMARY KEY (`idGrupo`))
ENGINE = InnoDB
AUTO_INCREMENT = 168
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bdgrc`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdgrc`.`usuario` (
  `idUsuario` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `usuarioValido` INT(11) NULL DEFAULT '0',
  `adminGlobal` INT(11) NULL DEFAULT '0',
  PRIMARY KEY (`idUsuario`))
ENGINE = InnoDB
AUTO_INCREMENT = 17
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bdgrc`.`referencia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdgrc`.`referencia` (
  `idReferencia` INT(11) NOT NULL AUTO_INCREMENT,
  `cita` VARCHAR(300) NULL DEFAULT NULL,
  `descripcion` VARCHAR(300) NULL DEFAULT NULL,
  `link` VARCHAR(300) NULL DEFAULT NULL,
  `fechaHora` DATETIME NOT NULL,
  `idUsuario` INT(11) NOT NULL,
  `idGrupo` INT(11) NOT NULL,
  PRIMARY KEY (`idReferencia`),
  INDEX `fk_Referencia_Usuario1_idx` (`idUsuario` ASC) VISIBLE,
  INDEX `fk_Referencia_Grupo1_idx` (`idGrupo` ASC) VISIBLE,
  CONSTRAINT `fk_Referencia_Grupo1`
    FOREIGN KEY (`idGrupo`)
    REFERENCES `bdgrc`.`grupo` (`idGrupo`),
  CONSTRAINT `fk_Referencia_Usuario1`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `bdgrc`.`usuario` (`idUsuario`))
ENGINE = InnoDB
AUTO_INCREMENT = 39
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bdgrc`.`comentario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdgrc`.`comentario` (
  `idComentario` INT(11) NOT NULL AUTO_INCREMENT,
  `comentario` VARCHAR(3000) NULL DEFAULT NULL,
  `fechaHora` DATETIME NOT NULL,
  `idReferencia` INT(11) NOT NULL,
  `idUsuario` INT(11) NOT NULL,
  PRIMARY KEY (`idComentario`, `idReferencia`, `idUsuario`),
  INDEX `fk_Comentario_Referencia1_idx` (`idReferencia` ASC) VISIBLE,
  INDEX `fk_Comentario_Usuario1_idx` (`idUsuario` ASC) VISIBLE,
  CONSTRAINT `fk_Comentario_Referencia1`
    FOREIGN KEY (`idReferencia`)
    REFERENCES `bdgrc`.`referencia` (`idReferencia`),
  CONSTRAINT `fk_Comentario_Usuario1`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `bdgrc`.`usuario` (`idUsuario`))
ENGINE = InnoDB
AUTO_INCREMENT = 39
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bdgrc`.`grupo_has_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdgrc`.`grupo_has_usuario` (
  `Grupo_idGrupo` INT(11) NOT NULL,
  `Usuario_idUsuario` INT(11) NOT NULL,
  `permisoUsuario` ENUM('creador', 'lectura', 'escritura') NULL DEFAULT NULL,
  PRIMARY KEY (`Grupo_idGrupo`, `Usuario_idUsuario`),
  INDEX `fk_Grupo_has_Usuario_Usuario1_idx` (`Usuario_idUsuario` ASC) VISIBLE,
  INDEX `fk_Grupo_has_Usuario_Grupo_idx` (`Grupo_idGrupo` ASC) VISIBLE,
  CONSTRAINT `fk_Grupo_has_Usuario_Grupo`
    FOREIGN KEY (`Grupo_idGrupo`)
    REFERENCES `bdgrc`.`grupo` (`idGrupo`),
  CONSTRAINT `fk_Grupo_has_Usuario_Usuario1`
    FOREIGN KEY (`Usuario_idUsuario`)
    REFERENCES `bdgrc`.`usuario` (`idUsuario`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bdgrc`.`tag`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdgrc`.`tag` (
  `idTag` INT(11) NOT NULL AUTO_INCREMENT,
  `etiqueta` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`idTag`))
ENGINE = InnoDB
AUTO_INCREMENT = 9
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bdgrc`.`tag_has_referencia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdgrc`.`tag_has_referencia` (
  `idTag` INT(11) NOT NULL,
  `idReferencia` INT(11) NOT NULL,
  PRIMARY KEY (`idTag`, `idReferencia`),
  INDEX `fk_Tag_has_Referencia_Referencia1_idx` (`idReferencia` ASC) VISIBLE,
  INDEX `fk_Tag_has_Referencia_Tag1_idx` (`idTag` ASC) VISIBLE,
  CONSTRAINT `fk_Tag_has_Referencia_Referencia1`
    FOREIGN KEY (`idReferencia`)
    REFERENCES `bdgrc`.`referencia` (`idReferencia`),
  CONSTRAINT `fk_Tag_has_Referencia_Tag1`
    FOREIGN KEY (`idTag`)
    REFERENCES `bdgrc`.`tag` (`idTag`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
